version: "3.8"

services:
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  web:
    build: .
    volumes:
      - ./log:/home/app/orangejuice/log
    secrets:
      - source: master_key
        target: /home/app/orangejuice/config/master.key
    ports:
      - "8001:80"
    depends_on:
      - db
      - redis

secrets:
  master_key:
    file: ./config/master.key

volumes:
  pgdata:
  redisdata:
